manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware/

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main # You can specify a different branch if needed
      import: app/west.yml
      path: zmk

  self:
    path: config
